name: Manual
on: 
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: Hello
                required: true
                description: 'Greeting to use'
            log-level:
                type: choice
                options:
                    - info
                    - warning
                    - error
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }} world!"